// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: pbft/v1/service.proto

package pbftv1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// 서버 인터페이스
type PBFTServiceClient interface {
	// 메시지 브로드캐스트
	BroadcastMessage(ctx context.Context, in *BroadcastMessageRequest, opts ...grpc.CallOption) (*BroadcastMessageResponse, error)
	// 특정 노드에 메시지 전송
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// MessageStream creates a bidirectional message stream.
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (PBFTService_MessageStreamClient, error)
	// SyncState synchronizes state between nodes.
	SyncState(ctx context.Context, in *SyncStateRequest, opts ...grpc.CallOption) (*SyncStateResponse, error)
	// GetCheckpoint retrieves a checkpoint.
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	// GetStatus returns the node status.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// BroadcastTx - 모든 피어에게 트랜잭션 브로드캐스트
	BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxResponse, error)
	// SendTx - 특정 피어에게 트랜잭션 전송
	SendTx(ctx context.Context, in *SendTxRequest, opts ...grpc.CallOption) (*SendTxResponse, error)
}

type pBFTServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewPBFTServiceClient creates a new PBFTServiceClient.
func NewPBFTServiceClient(cc grpc.ClientConnInterface) PBFTServiceClient {
	return &pBFTServiceClient{cc}
}

func (c *pBFTServiceClient) BroadcastMessage(ctx context.Context, in *BroadcastMessageRequest, opts ...grpc.CallOption) (*BroadcastMessageResponse, error) {
	out := new(BroadcastMessageResponse)
	err := c.cc.Invoke(ctx, "/pbft.v1.PBFTService/BroadcastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/pbft.v1.PBFTService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTServiceClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (PBFTService_MessageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &PBFTService_ServiceDesc.Streams[0], "/pbft.v1.PBFTService/MessageStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pBFTServiceMessageStreamClient{stream}
	return x, nil
}

type PBFTService_MessageStreamClient interface {
	Send(*PBFTMessage) error
	Recv() (*PBFTMessage, error)
	grpc.ClientStream
}

type pBFTServiceMessageStreamClient struct {
	grpc.ClientStream
}

func (x *pBFTServiceMessageStreamClient) Send(m *PBFTMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pBFTServiceMessageStreamClient) Recv() (*PBFTMessage, error) {
	m := new(PBFTMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pBFTServiceClient) SyncState(ctx context.Context, in *SyncStateRequest, opts ...grpc.CallOption) (*SyncStateResponse, error) {
	out := new(SyncStateResponse)
	err := c.cc.Invoke(ctx, "/pbft.v1.PBFTService/SyncState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, "/pbft.v1.PBFTService/GetCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/pbft.v1.PBFTService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTServiceClient) BroadcastTx(ctx context.Context, in *BroadcastTxRequest, opts ...grpc.CallOption) (*BroadcastTxResponse, error) {
	out := new(BroadcastTxResponse)
	err := c.cc.Invoke(ctx, "/pbft.v1.PBFTService/BroadcastTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTServiceClient) SendTx(ctx context.Context, in *SendTxRequest, opts ...grpc.CallOption) (*SendTxResponse, error) {
	out := new(SendTxResponse)
	err := c.cc.Invoke(ctx, "/pbft.v1.PBFTService/SendTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// 서버 인터페이스
type PBFTServiceServer interface {
	// 모든 피어에게 PBFT 메시지 브로드 캐스트
	BroadcastMessage(context.Context, *BroadcastMessageRequest) (*BroadcastMessageResponse, error)
	// SendMessange - 특정 노드에 PBFT 메시지 전송
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// MessageStream - 양방향 메시지 스트림
	MessageStream(PBFTService_MessageStreamServer) error
	// SyncState - 노드 간 상태 동기화 (블록, 체크 포인트)
	SyncState(context.Context, *SyncStateRequest) (*SyncStateResponse, error)
	// GetCheckpoint retrieves a checkpoint.
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
	// GetStatus returns the node status.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// BroadcastTx - 모든 피어에게 트랜잭션 브로드캐스트
	BroadcastTx(context.Context, *BroadcastTxRequest) (*BroadcastTxResponse, error)
	// SendTx - 특정 피어에게 트랜잭션 전송
	SendTx(context.Context, *SendTxRequest) (*SendTxResponse, error)
	mustEmbedUnimplementedPBFTServiceServer()
}

// UnimplementedPBFTServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPBFTServiceServer struct{}

func (UnimplementedPBFTServiceServer) BroadcastMessage(context.Context, *BroadcastMessageRequest) (*BroadcastMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessage not implemented")
}
func (UnimplementedPBFTServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedPBFTServiceServer) MessageStream(PBFTService_MessageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedPBFTServiceServer) SyncState(context.Context, *SyncStateRequest) (*SyncStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncState not implemented")
}
func (UnimplementedPBFTServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedPBFTServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPBFTServiceServer) BroadcastTx(context.Context, *BroadcastTxRequest) (*BroadcastTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastTx not implemented")
}
func (UnimplementedPBFTServiceServer) SendTx(context.Context, *SendTxRequest) (*SendTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTx not implemented")
}
func (UnimplementedPBFTServiceServer) mustEmbedUnimplementedPBFTServiceServer() {}

// UnsafePBFTServiceServer may be embedded to opt out of forward compatibility.
type UnsafePBFTServiceServer interface {
	mustEmbedUnimplementedPBFTServiceServer()
}

type PBFTService_MessageStreamServer interface {
	Send(*PBFTMessage) error
	Recv() (*PBFTMessage, error)
	grpc.ServerStream
}

type pBFTServiceMessageStreamServer struct {
	grpc.ServerStream
}

func (x *pBFTServiceMessageStreamServer) Send(m *PBFTMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pBFTServiceMessageStreamServer) Recv() (*PBFTMessage, error) {
	m := new(PBFTMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegisterPBFTServiceServer registers the PBFTServiceServer to a grpc.Server.
func RegisterPBFTServiceServer(s grpc.ServiceRegistrar, srv PBFTServiceServer) {
	s.RegisterService(&PBFTService_ServiceDesc, srv)
}

func _PBFTService_BroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTServiceServer).BroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbft.v1.PBFTService/BroadcastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTServiceServer).BroadcastMessage(ctx, req.(*BroadcastMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbft.v1.PBFTService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTService_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PBFTServiceServer).MessageStream(&pBFTServiceMessageStreamServer{stream})
}

func _PBFTService_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTServiceServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbft.v1.PBFTService/SyncState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTServiceServer).SyncState(ctx, req.(*SyncStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbft.v1.PBFTService/GetCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbft.v1.PBFTService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTService_BroadcastTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTServiceServer).BroadcastTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbft.v1.PBFTService/BroadcastTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTServiceServer).BroadcastTx(ctx, req.(*BroadcastTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTService_SendTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTServiceServer).SendTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbft.v1.PBFTService/SendTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTServiceServer).SendTx(ctx, req.(*SendTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PBFTService_ServiceDesc is the grpc.ServiceDesc for PBFTService service.
var PBFTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.v1.PBFTService",
	HandlerType: (*PBFTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastMessage",
			Handler:    _PBFTService_BroadcastMessage_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _PBFTService_SendMessage_Handler,
		},
		{
			MethodName: "SyncState",
			Handler:    _PBFTService_SyncState_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _PBFTService_GetCheckpoint_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PBFTService_GetStatus_Handler,
		},
		{
			MethodName: "BroadcastTx",
			Handler:    _PBFTService_BroadcastTx_Handler,
		},
		{
			MethodName: "SendTx",
			Handler:    _PBFTService_SendTx_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _PBFTService_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pbft/v1/service.proto",
}

// Request/Response types

// BroadcastMessageRequest is the request for BroadcastMessage.
type BroadcastMessageRequest struct {
	Message *PBFTMessage `json:"message,omitempty"`
}

// BroadcastMessageResponse is the response for BroadcastMessage.
type BroadcastMessageResponse struct {
	Success bool   `json:"success,omitempty"`
	Error   string `json:"error,omitempty"`
}

// SendMessageRequest is the request for SendMessage.
type SendMessageRequest struct {
	TargetNodeId string       `json:"target_node_id,omitempty"`
	Message      *PBFTMessage `json:"message,omitempty"`
}

// SendMessageResponse is the response for SendMessage.
type SendMessageResponse struct {
	Success bool   `json:"success,omitempty"`
	Error   string `json:"error,omitempty"`
}

// SyncStateRequest is the request for SyncState.
type SyncStateRequest struct {
	FromHeight uint64 `json:"from_height,omitempty"`
	ToHeight   uint64 `json:"to_height,omitempty"`
}

// SyncStateResponse is the response for SyncState.
type SyncStateResponse struct {
	Blocks      []*Block      `json:"blocks,omitempty"`
	Checkpoints []*Checkpoint `json:"checkpoints,omitempty"`
}

// GetCheckpointRequest is the request for GetCheckpoint.
type GetCheckpointRequest struct {
	SequenceNum uint64 `json:"sequence_num,omitempty"`
}

// GetCheckpointResponse is the response for GetCheckpoint.
type GetCheckpointResponse struct {
	Checkpoint *Checkpoint `json:"checkpoint,omitempty"`
	StateHash  []byte      `json:"state_hash,omitempty"`
}

// GetStatusRequest is the request for GetStatus.
type GetStatusRequest struct{}

// GetStatusResponse is the response for GetStatus.
type GetStatusResponse struct {
	NodeId        string `json:"node_id,omitempty"`
	CurrentView   uint64 `json:"current_view,omitempty"`
	CurrentHeight uint64 `json:"current_height,omitempty"`
	LastAppHash   []byte `json:"last_app_hash,omitempty"`
	PeerCount     int32  `json:"peer_count,omitempty"`
	IsPrimary     bool   `json:"is_primary,omitempty"`
}

// GetMessage returns the message from the request.
func (r *BroadcastMessageRequest) GetMessage() *PBFTMessage {
	if r != nil {
		return r.Message
	}
	return nil
}

// GetMessage returns the message from the request.
func (r *SendMessageRequest) GetMessage() *PBFTMessage {
	if r != nil {
		return r.Message
	}
	return nil
}

// GetTargetNodeId returns the target node ID from the request.
func (r *SendMessageRequest) GetTargetNodeId() string {
	if r != nil {
		return r.TargetNodeId
	}
	return ""
}
