// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbft/v1/types.proto
// 전체적인 메시지 타입을 정의하고 구조체를 정의하는 패키지임
package pbftv1

import (
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// MessageType represents the type of PBFT message.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_PRE_PREPARE MessageType = 1 // 리더가 블록 제안
	MessageType_MESSAGE_TYPE_PREPARE     MessageType = 2 // 검증자가 제안 승인
	MessageType_MESSAGE_TYPE_COMMIT      MessageType = 3 // 검증자가 커밋 준비
	MessageType_MESSAGE_TYPE_VIEW_CHANGE MessageType = 4 // 뷰 변경 요청
	MessageType_MESSAGE_TYPE_NEW_VIEW    MessageType = 5 // 새 뷰 시작
	MessageType_MESSAGE_TYPE_CHECKPOINT  MessageType = 6 // 체크 포인트
)

// PBFTMessage represents a PBFT consensus message for network transmission.
type PBFTMessage struct {
	Type        MessageType            `json:"type,omitempty"` // 메시지 타입
	View        uint64                 `json:"view,omitempty"` // 현재 뷰 번호
	SequenceNum uint64                 `json:"sequence_num,omitempty"` // 시퀸스 번호 블록 높이
	Digest      []byte                 `json:"digest,omitempty"` // 블록/데이터 해시
	NodeId      string                 `json:"node_id,omitempty"` // 발신 노드 ID
	Timestamp   *timestamppb.Timestamp `json:"timestamp,omitempty"` // 타임스탬프
	Signature   []byte                 `json:"signature,omitempty"` // 서명
	Payload     []byte                 `json:"payload,omitempty"` // 실제 데이터
}

// PrePrepareMsg 메시지 구조
type PrePrepareMsg struct {
	View        uint64 `json:"view,omitempty"` // 뷰 번호
	SequenceNum uint64 `json:"sequence_num,omitempty"` // 시퀸스 번호 블록 높이
	Digest      []byte `json:"digest,omitempty"` // 블록 해시
	BlockData   []byte `json:"block_data,omitempty"` // 블록 데이터
	PrimaryId   string `json:"primary_id,omitempty"` // 리더 노드 ID
}

// PrepareMsg 메시지 구조
type PrepareMsg struct {
	View        uint64 `json:"view,omitempty"` // 뷰 번호
	SequenceNum uint64 `json:"sequence_num,omitempty"` // 시퀸스 번호
	Digest      []byte `json:"digest,omitempty"` // 블록 해시 
	NodeId      string `json:"node_id,omitempty"` // 노드 ID
}

// CommitMsg 메시지 구조
type CommitMsg struct {
	View        uint64 `json:"view,omitempty"` // 뷰 번호
	SequenceNum uint64 `json:"sequence_num,omitempty"` // 시퀸스 번호
	Digest      []byte `json:"digest,omitempty"` // 다이제스트
	NodeId      string `json:"node_id,omitempty"` // 노드 ID
}

// ViewChangeMsg 메시지 구조
type ViewChangeMsg struct {
	NewView     uint64          `json:"new_view,omitempty"` // 새로운 뷰
	LastSeqNum  uint64          `json:"last_seq_num,omitempty"` // 마지막 안정 블록 높이
	Checkpoints []*Checkpoint   `json:"checkpoints,omitempty"` // 전까지 처리하던 트랜잭션
	PreparedSet []*PreparedCert `json:"prepared_set,omitempty"` // 준비된 인증서들
	NodeId      string          `json:"node_id,omitempty"` // 노드 ID
}

// NewViewMsg 메시지 구조 이건 뷰가 확정되었을 때 하는거임 새로운 뷰 체인지가 결정되었을 때
type NewViewMsg struct {
	View           uint64           `json:"view,omitempty"` // 새 뷰 번호
	ViewChangeMsgs []*ViewChangeMsg `json:"view_change_msgs,omitempty"` // 뷰 변경 메시지들
	PrePrepareMsgs []*PrePrepareMsg `json:"pre_prepare_msgs,omitempty"` // 새 뷰의 PrePrepare들
	NewPrimaryId   string           `json:"new_primary_id,omitempty"` // 새 리더 노드 ID
}

// Checkpoint는 안정적인 체크포인트를 나타냄
type Checkpoint struct {
	SequenceNum uint64 `json:"sequence_num,omitempty"` // 시퀸스 번호
	Digest      []byte `json:"digest,omitempty"` // 상태 다이제스트
	NodeId      string `json:"node_id,omitempty"` // 노드 ID
}

// PreparedCert는 prepared 된 증명서를 나타낸다
type PreparedCert struct {
	PrePrepare *PrePrepareMsg `json:"pre_prepare,omitempty"` // PrePrepareMsg 구조체의 주소를 저장한다 이렇게 구조체 자체가 임베딩되는 경우에는 전체값 복사를 웬만하면 하지않고 주소를 저장함
	Prepares   []*PrepareMsg  `json:"prepares,omitempty"` // Prepare 메시지들
}

// BlockHeader는 블록 헤더를 나타낸다
type BlockHeader struct {
	Height    uint64                 `json:"height,omitempty"` // 블록 높이이다.
	Timestamp *timestamppb.Timestamp `json:"timestamp,omitempty"` // 타임스탬프 
	PrevHash  []byte                 `json:"prev_hash,omitempty"` // 이전 블록 해시
	TxHash    []byte                 `json:"tx_hash,omitempty"` // 트랜잭션 머클 루트
	StateHash []byte                 `json:"state_hash,omitempty"` // 상태 해시
	Proposer  string                 `json:"proposer,omitempty"` // 제안자 ID
	View      uint64                 `json:"view,omitempty"` // 뷰 번호
}

// Block는 블록을 나타낸다.
type Block struct {
	Header *BlockHeader `json:"header,omitempty"` // 블록헤더임. 마찬가지로 블록 헤더 자체 구조체의 크기가 크기 때문에 주소를 저장한다.
	Txs    [][]byte     `json:"txs,omitempty"` // 트랜잭션들
	Hash   []byte       `json:"hash,omitempty"` // 블록 해시
}

// Transaction은 트랜잭션을 나타낸다.
type Transaction struct {
	Id        string                 `json:"id,omitempty"`  // 트랜잭션 ID
	Data      []byte                 `json:"data,omitempty"` // 트랜잭션 데이터
	Timestamp *timestamppb.Timestamp `json:"timestamp,omitempty"` // 타임 스탬프
	Signature []byte                 `json:"signature,omitempty"` // 서명
	From      string                 `json:"from,omitempty"` // 발신자
}

// Validator는 벨리데이터(검증자)를 나타낸다.
type Validator struct {
	Id          string `json:"id,omitempty"` // 검증자 ID
	PubKey      []byte `json:"pub_key,omitempty"` // 공개키 
	VotingPower int64  `json:"voting_power,omitempty"` // 투표력
}

// ValidatorSet는 벨리데이터들의 집합을 나타낸다.
type ValidatorSet struct {
	Validators []*Validator `json:"validators,omitempty"` // 벨리데이터들 목록(주소 배열이다.[0x1, 0x2,....])
}

// Helper 함수들

// GetType returns the message type.
func (m *PBFTMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

// GetView returns the view number.
func (m *PBFTMessage) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

// GetSequenceNum returns the sequence number.
func (m *PBFTMessage) GetSequenceNum() uint64 {
	if m != nil {
		return m.SequenceNum
	}
	return 0
}

// GetDigest returns the digest.
func (m *PBFTMessage) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

// GetNodeId returns the node ID.
func (m *PBFTMessage) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// GetTimestamp returns the timestamp.
func (m *PBFTMessage) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// GetSignature returns the signature.
func (m *PBFTMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// GetPayload returns the payload.
func (m *PBFTMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// TimestampToTime converts a protobuf timestamp to Go time.
func TimestampToTime(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

// TimeToTimestamp converts a Go time to protobuf timestamp.
func TimeToTimestamp(t time.Time) *timestamppb.Timestamp {
	return timestamppb.New(t)
}
