// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbft/v1/types.proto

package pbftv1

import (
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// MessageType represents the type of PBFT message.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_PRE_PREPARE MessageType = 1
	MessageType_MESSAGE_TYPE_PREPARE     MessageType = 2
	MessageType_MESSAGE_TYPE_COMMIT      MessageType = 3
	MessageType_MESSAGE_TYPE_VIEW_CHANGE MessageType = 4
	MessageType_MESSAGE_TYPE_NEW_VIEW    MessageType = 5
	MessageType_MESSAGE_TYPE_CHECKPOINT  MessageType = 6
)

// PBFTMessage represents a PBFT consensus message for network transmission.
type PBFTMessage struct {
	Type        MessageType            `json:"type,omitempty"`
	View        uint64                 `json:"view,omitempty"`
	SequenceNum uint64                 `json:"sequence_num,omitempty"`
	Digest      []byte                 `json:"digest,omitempty"`
	NodeId      string                 `json:"node_id,omitempty"`
	Timestamp   *timestamppb.Timestamp `json:"timestamp,omitempty"`
	Signature   []byte                 `json:"signature,omitempty"`
	Payload     []byte                 `json:"payload,omitempty"`
}

// PrePrepareMsg contains the pre-prepare message data.
type PrePrepareMsg struct {
	View        uint64 `json:"view,omitempty"`
	SequenceNum uint64 `json:"sequence_num,omitempty"`
	Digest      []byte `json:"digest,omitempty"`
	BlockData   []byte `json:"block_data,omitempty"`
	PrimaryId   string `json:"primary_id,omitempty"`
}

// PrepareMsg contains the prepare message data.
type PrepareMsg struct {
	View        uint64 `json:"view,omitempty"`
	SequenceNum uint64 `json:"sequence_num,omitempty"`
	Digest      []byte `json:"digest,omitempty"`
	NodeId      string `json:"node_id,omitempty"`
}

// CommitMsg contains the commit message data.
type CommitMsg struct {
	View        uint64 `json:"view,omitempty"`
	SequenceNum uint64 `json:"sequence_num,omitempty"`
	Digest      []byte `json:"digest,omitempty"`
	NodeId      string `json:"node_id,omitempty"`
}

// ViewChangeMsg contains the view change message data.
type ViewChangeMsg struct {
	NewView     uint64          `json:"new_view,omitempty"`
	LastSeqNum  uint64          `json:"last_seq_num,omitempty"`
	Checkpoints []*Checkpoint   `json:"checkpoints,omitempty"`
	PreparedSet []*PreparedCert `json:"prepared_set,omitempty"`
	NodeId      string          `json:"node_id,omitempty"`
}

// NewViewMsg contains the new view message data.
type NewViewMsg struct {
	View           uint64           `json:"view,omitempty"`
	ViewChangeMsgs []*ViewChangeMsg `json:"view_change_msgs,omitempty"`
	PrePrepareMsgs []*PrePrepareMsg `json:"pre_prepare_msgs,omitempty"`
	NewPrimaryId   string           `json:"new_primary_id,omitempty"`
}

// Checkpoint represents a stable checkpoint.
type Checkpoint struct {
	SequenceNum uint64 `json:"sequence_num,omitempty"`
	Digest      []byte `json:"digest,omitempty"`
	NodeId      string `json:"node_id,omitempty"`
}

// PreparedCert represents a prepared certificate.
type PreparedCert struct {
	PrePrepare *PrePrepareMsg `json:"pre_prepare,omitempty"`
	Prepares   []*PrepareMsg  `json:"prepares,omitempty"`
}

// BlockHeader represents a block header.
type BlockHeader struct {
	Height    uint64                 `json:"height,omitempty"`
	Timestamp *timestamppb.Timestamp `json:"timestamp,omitempty"`
	PrevHash  []byte                 `json:"prev_hash,omitempty"`
	TxHash    []byte                 `json:"tx_hash,omitempty"`
	StateHash []byte                 `json:"state_hash,omitempty"`
	Proposer  string                 `json:"proposer,omitempty"`
	View      uint64                 `json:"view,omitempty"`
}

// Block represents a block.
type Block struct {
	Header *BlockHeader `json:"header,omitempty"`
	Txs    [][]byte     `json:"txs,omitempty"`
	Hash   []byte       `json:"hash,omitempty"`
}

// Transaction represents a transaction.
type Transaction struct {
	Id        string                 `json:"id,omitempty"`
	Data      []byte                 `json:"data,omitempty"`
	Timestamp *timestamppb.Timestamp `json:"timestamp,omitempty"`
	Signature []byte                 `json:"signature,omitempty"`
	From      string                 `json:"from,omitempty"`
}

// Validator represents a validator.
type Validator struct {
	Id          string `json:"id,omitempty"`
	PubKey      []byte `json:"pub_key,omitempty"`
	VotingPower int64  `json:"voting_power,omitempty"`
}

// ValidatorSet represents a set of validators.
type ValidatorSet struct {
	Validators []*Validator `json:"validators,omitempty"`
}

// Helper functions

// GetType returns the message type.
func (m *PBFTMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

// GetView returns the view number.
func (m *PBFTMessage) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

// GetSequenceNum returns the sequence number.
func (m *PBFTMessage) GetSequenceNum() uint64 {
	if m != nil {
		return m.SequenceNum
	}
	return 0
}

// GetDigest returns the digest.
func (m *PBFTMessage) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

// GetNodeId returns the node ID.
func (m *PBFTMessage) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// GetTimestamp returns the timestamp.
func (m *PBFTMessage) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// GetSignature returns the signature.
func (m *PBFTMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// GetPayload returns the payload.
func (m *PBFTMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// TimestampToTime converts a protobuf timestamp to Go time.
func TimestampToTime(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

// TimeToTimestamp converts a Go time to protobuf timestamp.
func TimeToTimestamp(t time.Time) *timestamppb.Timestamp {
	return timestamppb.New(t)
}
